WEBSV5TOT/Areas/Admin/Controllers/ApprovalController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using WEBSV5TOT.Models;
using WEBSV5TOT.ViewModel;

namespace WEBSV5TOT.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin,banthuky")]
    [Area("Admin")]
    public class ApprovalController : Controller
    {
        private readonly Sv5totContext db;
        private readonly IWebHostEnvironment _environment;
        public ApprovalController(Sv5totContext db, IWebHostEnvironment environment)
        {
            this.db = db;
            _environment = environment; 
        }
        public IActionResult Index()
        {
            var lst = db.Student5Goods
                .Where(student => student.ProofPictures.Any(picture => picture.Student5GoodId == student.Id))
                .OrderByDescending(x=>x.Id)
                .ToList(); ;
            ViewBag.ProofPictures = db.ProofPictures.ToList();
            ViewBag.Users = db.Users.ToList();
            ViewBag.Activities = db.Activities.ToList();
            return View(lst);
        }

        public IActionResult _ImageList(int id)
        {
            List<ProofPicture> images = db.ProofPictures.Where(p => p.Student5GoodId == id).ToList();

            return PartialView("_ImageList", images);
        }
        [HttpGet]
        public ActionResult GetImage(string fileName)
        {
            // Đường dẫn tệp hình ảnh
            string imagePath = Path.Combine(_environment.ContentRootPath, "Proofs", fileName);

            // Kiểm tra xem tệp có tồn tại không
            if (System.IO.File.Exists(imagePath))
            {
                // Trả về hình ảnh
                return File(imagePath, "image/jpeg"); // Thay đổi "image/jpeg" thành kiểu MIME của hình ảnh của bạn
            }
            else
            {
                return Json(new { status = false });
            }
        }

        [HttpPost]
        public IActionResult Approve(int id)
        {
            var sv5t = db.Student5Goods.Where(x => x.Id == id).SingleOrDefault();
            if(sv5t != null)
            {
                sv5t.Approval = true;
                db.SaveChanges();
            }
                
            return Json(new { status = true });
        }
        [HttpPost]
        public IActionResult DisApprove(int id)
        {
            var sv5t = db.Student5Goods.Where(x => x.Id == id).SingleOrDefault();
            if (sv5t != null)
            {
                sv5t.Approval = false;
                db.SaveChanges();
            }

            return Json(new { status = true });
        }
    }
}

WEBSV5TOT/Areas/Admin/Views/Approval/Index.cshtml
@using WEBSV5TOT.Models;
@model IEnumerable<WEBSV5TOT.Models.Student5Good>
@{
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
    ViewData["Title"] = "Danh sách hoạt động";
    var listPic = ViewBag.ProofPictures as List<ProofPicture>;
    var listUsers = ViewBag.Users as List<User>;
    var listAc = ViewBag.Activities as List<Activity>;
}

<div class="card">
    <div class="card-header">

        <div class="row justify-content-between align-items-center">
            <h3 class="card-title">Danh sách chờ duyệt</h3>
        </div>

    </div>
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr class="text-center">
                    <th>STT</th>
                    <th>Tên hoạt động</th>
                    <th>Tên sinh viên</th>
                    <th>Ngày nộp minh chứng</th>
                    <th>Ngày hoạt động</th>
                    <th>Ảnh minh chứng</th>
                    <th>Duyệt</th>
                </tr>
            </thead>
            <tbody>

                @if (Model != null)
                {
                    int stt = 1;

                    foreach (var item in Model)
                    {
                       @* Activity? activity = listAc.SingleOrDefault(x => x != null && x.Id == item.ActivityId);
                        User? user = listUsers.SingleOrDefault(x => x != null && x.Id == item.UserId); ;
                        if (activity == null || user == null){
                            continue;
                        }*@
                            
                        <tr>
                            <td class="text-center">@stt</td>
                            <td>@(listAc?.FirstOrDefault(x => x.Id == item.ActivityId)?.Name)</td>
                            <td>@(listUsers?.FirstOrDefault(x => x.Id == item.UserId)?.FullName)</td>
                            <td>@listPic?.FirstOrDefault(x => x.Student5GoodId == item.Id)?.InputDate.ToString("dd/MM/yyyy")</td>
                            <td>@item.Year</td>
                            <td class="text-center"><button data-id="@item.Id" class="btnview btn btn-secondary join" data-toggle="modal" data-target="#viewModal">Xem minh chứng</button></td>
                            <td class="text-center">
                                @if(item.Approval == false)
                                {
                                    <button  data-id="@item.Id" class="btnapprove btn btn-success join">Duyệt</button>
                                }
                                else
                                {
                                    <button data-id="@item.Id" class="btndisapprove btn btn-danger join">Hủy duyệt</button>
                                }
                            </td>
                        </tr>
                        stt++;
                    }
                }
                
            </tbody>
        </table>
    </div>
    <div class="modal fade" id="viewModal" tabindex="-1" role="dialog" aria-labelledby="viewModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="uploadModalLabel">Ảnh minh chứng</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="listimage">
                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                </div>
            </div>
        </div>
    </div>


    <div class="card-footer">
    </div>
</div>
@section Scripts {
    <script>
        
        $('.btnview').on('click', function () {
            var data_id = this.getAttribute('data-id');
            $.ajax({
                url: "/admin/Approval/_ImageList/" + data_id,
                type: "GET",
                success: function (result) {
                    $("#listimage").html(result);
                },
                error: function (error) {
                    console.log("Error:", error);
                }
            });
        });
        function addEventLisBtnApprove(){
            $('.btnapprove').on('click', function () {
                var data_id = this.getAttribute('data-id');
                $(this).closest("td").html('<button data-id="' + data_id + '" class="btndisapprove btn btn-danger join">Hủy duyệt</button>');
                
                $.ajax({
                    url: "/admin/Approval/Approve/" + data_id,
                    type: "POST",
                    success: function () {
                        showToast("success", "Đã duyệt thành công", 2500);
                        addEventLisBtnDisApprove();
                    },
                    error: function (error) {
                        showToast("error", "Duyệt thất bại", 2500);
                    }
                });
            });
        }
        

        function addEventLisBtnDisApprove() {
            $('.btndisapprove').on('click', function () {
                var data_id = this.getAttribute('data-id');
                $(this).closest("td").html('<button data-id="' + data_id + '"class="btnapprove btn btn-success join">Duyệt</button>');
                
                $.ajax({
                    url: "/admin/Approval/DisApprove/" + data_id,
                    type: "POST",
                    success: function () {
                        showToast("success", "Đã hủy thành công", 2500);
                        addEventLisBtnApprove();
                    },
                    error: function (error) {
                        showToast("error", "Hủy thất bại", 2500);
                    }
                });
            });
        }

        addEventLisBtnApprove();
        addEventLisBtnDisApprove();



        $("#example1").DataTable({
            "responsive": true, "lengthChange": false, "autoWidth": false,
            "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });
    </script>
}

WEBSV5TOT/Areas/Admin/Views/Approval/_ImageList.cshtml
@model List<WEBSV5TOT.Models.ProofPicture>

@foreach (var image in Model)
{
    <img src="~/Proofs/@image.FileName" style="width:200px;height:auto;" />
    @*<img src="@Url.Action("GetImage", "Approval", new { fileName = image.FileName })" alt="Proof Image" />*@
}